### ISSUE TITLE
Transparent pixels in PNGs are being calculated as white

### ISSUE THREAD

**Issue by munsonbh** [zumbov2/colorfindr#2]
Hello, and first thank you for building this! I have been playing with it quite a bit for a project, and I ran into a roadblock. If I feed a png with transparency, R calculates those pixels as white and it overwhelms the tree graph. Is there a simple way to fix this? Thanks again!

**Comment by zumbov2** [comment]
Hi @munsonbh, thank you very much for your feedback. May I ask you which version of colorfindr you are using? The issue with the transparent colors should have been fixed with version colorfindr 0.1.2 (see [NEWS](https://github.com/zumbov2/colorfindr/blob/master/NEWS)).
